# Configuraci贸n para el Repositorio

blank_issues_enabled: false
contact_links:
  - name:  GitHub Discussions
    url: https://github.com/elparchetipk/bc-oop-java/discussions
    about: Haz preguntas generales, comparte ideas o inicia conversaciones con la comunidad
  - name:  Documentaci贸n
    url: https://github.com/elparchetipk/bc-oop-java/blob/main/README.md
    about: Lee la documentaci贸n completa del bootcamp
  - name:  Gu铆a de Contribuci贸n
    url: https://github.com/elparchetipk/bc-oop-java/blob/main/CONTRIBUTING.md
    about: Aprende c贸mo contribuir al proyecto
